### ISSUE TITLE
Parameter "secured" in config.yml is not working

### ISSUE THREAD

**Issue by romain3w** [mailjet/mailjetBundle#18]
Here my config.yml file :
```
mailjet:
    api_key:    %mailjet_api%
    secret_key: %mailjet_secret%
    options:
        version: "v3.1"
        secured: true
    transactionnal:
        options:
            version: "v3.1"
            secured: true
```

Even when I force secured to True value, the request call HTTP

A dump on $mailjet = $this->container->get('mailjet.client');
let me see that the parameter is not used from my config.yml

```
MailjetClient {
  #calls: []
  -apikey: "xxxxx"
  -apisecret: "xxxxx"
  -apitoken: null
  -version: "v3.1"
  -url: "api.mailjet.com"
  -secure: false
  -call: true
}
```

It's really annoying because v3.1 only accept HTTPS request
